---
DEFAULT:
- :bwa_ref: "/shared/gatk_resources/2.3/b37/bwa_7_6_indexed/human_g1k_v37.fasta"
  :gatk_ref: "/shared/gatk_resources/2.3/b37/bwa_7_6_indexed/human_g1k_v37.fasta"
  :snp_rod: "/shared/gatk_resources/2.8/b37/dbsnp_138.b37.vcf.gz"
  :interval_file: "/shared/metadata/intervals/clinical_research_exome.interval_list"
  :known_indels:
  - "/shared/gatk_resources/2.8/b37/1000G_phase1.indels.b37.vcf.gz"
  - "/shared/gatk_resources/2.8/b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
  :recalibration_known_sites:
  - "/shared/gatk_resources/2.8/b37/dbsnp_138.b37.vcf.gz"
  - "/shared/gatk_resources/2.8/b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
  :keep_unaligned: false
  :quality_type: Standard
  :mode: dna
  :opts:
    :skip_gvcf: false
    :skip_indel_realign: true
    :scheduler_opts: "-A an-account -p a-queue"
    :tmp_dir_base: "/scratch"
  :vqsr_snp:
    :variant_recalibrator_opts:
      :maxGaussians: 6
      :mode: SNP
    :apply_recalibration_opts:
      :mode: SNP
      :ts_filter_level: 99.5
    :training_sets:
    - :name: hapmap
      :type: VCF
      :path: "/shared/gatk_resources/2.8/b37/hapmap_3.3.b37.vcf.gz"
      :params: known=false,training=true,truth=true,prior=15.0
    - :name: omni
      :type: VCF
      :path: "/shared/gatk_resources/2.8/b37/1000G_omni2.5.b37.vcf.gz"
      :params: known=false,training=true,truth=false,prior=12.0
    - :name: 1000G
      :type: VCF
      :path: "/shared/gatk_resources/2.8/b37/1000G_phase1.snps.high_confidence.b37.vcf.gz"
      :params: known=false,training=true,truth=false,prior=10.0
    - :name: dbsnp
      :type: VCF
      :path: "/shared/gatk_resources/2.8/b37/dbsnp_138.b37.vcf.gz"
      :params: known=true,training=false,truth=false,prior=6.0
    :annotations:
    - MQRankSum
    - ReadPosRankSum
    - FS
    - DP
    - QD
    - SOR
  :vqsr_indel:
    :variant_recalibrator_opts:
      :maxGaussians: 4
      :mode: INDEL
      :stdThreshold: 10.0
    :apply_recalibration_opts:
      :mode: INDEL
      :ts_filter_level: 99.0
    :training_sets:
    - :name: mills
      :type: VCF
      :path: "/shared/gatk_resources/2.8/b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
      :params: known=true,training=true,truth=true,prior=12.0
    - :name: dbsnp
      :type: VCF
      :path: "/shared/gatk_resources/2.8/b37/dbsnp_138.b37.vcf.gz"
      :params: known=true,training=false,truth=false,prior=2.0
    :annotations:
    - MQRankSum
    - ReadPosRankSum
    - FS
    - DP
    - QD
    - SOR
NA08752:
- :run: a-run-name
  :is_paired: true
  :lane: a-lane-library-designation
  :inputs:
  - /path/to/read_1_fastq/NA08752-1/H7HTNAFXX/ngs-ky481ac544_S2_R1_001.fastq.xz
  - /path/to/read_2_fastq/NA08752-1/H7HTNAFXX/ngs-ky481ac544_S2_R2_001.fastq.xz
- :run: another-run-name
  :is_paired: true
  :lane: another-lane-library-designation
  :inputs:
  - /path/to/other_run/read_1_fastq/NA08752-1/HWVMFBGXX/ngs-ky481ac544_S3_R1_001.fastq.xz
  - /path/to/other_run/read_1_fastq/NA08752-1/HWVMFBGXX/ngs-ky481ac544_S3_R2_001.fastq.xz
